### ISSUE TITLE
Typescript file glob pattern not working properly

### ISSUE THREAD

**Issue by TomKriek** [antfu/eslint-plugin-unimport#1]
### Describe the bug

Heya,

Loving the plugin so far it's saving a lot of headaches when it comes to .vue components.
But as of right now the .ts files are being ignored even though there is a glob pattern set up for it.

[src/configs/auto-insert.ts](https://github.com/antfu/eslint-plugin-unimport/blob/main/src/configs/auto-insert.ts#L29)

[I tinkered real quick with an only testing tool from digital ocean for repo for globbing.](https://www.digitalocean.com/community/tools/glob?comments=true&glob=%2A%2A%2F%2A.%3F%28m%7Cc%29ts%3F%28x%29&matches=false&tests=composables%2Fcomposable.ts&tests=composables%2Fcomposable.ctsx&tests=composables%2Fcomposable.cjsx&tests=composables%2Fcomposable.cs&tests=src%2Fruntime%2Fcomposables%2Fcomposable.ts&tests=src%2Fruntime%2Fcomposables%2Fcomposable.js&tests=src%2Fruntime%2Fcomposables%2Fcomposable.ms&tests=src%2Fruntime%2Fcomposables%2Fcomposable.mts)

[Versus the current glob pattern](https://www.digitalocean.com/community/tools/glob?comments=true&glob=%2A%2A%2F%2A.%28m%7Cc%29%3Ftsx%3F&matches=false&tests=composables%2Fcomposable.ts&tests=composables%2Fcomposable.ctsx&tests=composables%2Fcomposable.cjsx&tests=composables%2Fcomposable.cs&tests=src%2Fruntime%2Fcomposables%2Fcomposable.ts&tests=src%2Fruntime%2Fcomposables%2Fcomposable.js&tests=src%2Fruntime%2Fcomposables%2Fcomposable.ms&tests=src%2Fruntime%2Fcomposables%2Fcomposable.mts)

`**/*.?(m|c)ts?(x)` seems to capture the .ts files properly.

Tested it locally by editing `node_modules/eslint-plugin-unimport/dist/index.mjs:221` real quick and works.

### Reproduction

See two attached glob tests

### System Info

```Shell
System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (4) x64 11th Gen Intel(R) Core(TM) i9-11950H @ 2.60GHz
    Memory: 14.91 GB / 15.62 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 18.20.3 - ~/.nvm/versions/node/v18.20.3/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 10.7.0 - ~/.nvm/versions/node/v18.20.3/bin/npm
    bun: 1.0.0 - ~/.bun/bin/bun
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by antfu** [comment]
Yeah you are right, the glob syntax in ESLint was different. Fixed in v0.1.1
